config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "tasks", to: "tasks#index"
  get "new", to: "tasks#new"
  post "tasks", to: "tasks#create"
  get "tasks/:id", to: "tasks#show", as: :task
  get "tasks/:id/edit", to: "tasks#edit", as: :edit_task
  patch "tasks/:id", to: "tasks#update"
  delete "tasks/:id", to: "tasks#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task.id)
  end

  def show
    @task = Task.find(params[:id])
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path, status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>

<%= form_with model: @task do |f| %>
  <div><%= f.label :title %></div>
  <div STYLE="margin-bottom:15px"><%= f.text_field :title %></div>
  <div><%= f.label :details %></div>
  <div STYLE="margin-bottom:15px"><%= f.text_field :details %></div>
  <div><%= f.label :completed? %></div>
  <div STYLE="margin-bottom:30px"><%= f.check_box :completed %></div>
  <button STYLE="margin-bottom:30px">Update task</button>
<% end %>

<%= link_to tasks_path do %>
  <small> ⃪ Back to list </small>
<% end %>

app/views/tasks/index.html.erb
<h1> Task list </h1>

<ul>
  <% @tasks.each do |task| %>
      <li> <%= task.completed %> <%= link_to task.title, task_path(task) %> </li>
  <% end %>
</ul>

<%= link_to new_path do %>
  <small> ✚ Add a new task </small>
<% end %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= form_with model: @root do |f| %>
  <div><%= f.label :title %></div>
  <div STYLE="margin-bottom:15px"><%= f.text_field :title %></div>
  <div><%= f.label :details %></div>
  <div STYLE="margin-bottom:30px"><%= f.text_field :details %></div>
  <button STYLE="margin-bottom:30px">Create task</button>
<% end %>

<%= link_to root_path do %>
  <small> ⃪ Back to list </small>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<p><%= @task.details  %></p>

<p> <%= @task.completed %> <%= @task.completed ? "This task is completed" : "This task is not completed yet"  %></p>

<div>
  <%= link_to edit_task_path do %>
    <button> ✍︎ Edit task </button>
  <% end %>
</div>

<div>
<%= link_to "Delete",
  task_path(@task),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>
</div>

<%= link_to tasks_path do %>
  <small> ⃪ Back to list </small>
<% end %>